/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dailycoding;

public class Solution {
  public double solution(int[] array) {

    double sum = 0;
    int divide = array.length;
    double average = 0;

    for (int i = 0; i < array.length; i += 1) {
      sum += array[i];
      average = sum / divide;
    }

    return average;
  }
}

