/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dailycoding;

public class SumDivisor {
  public int solution(int number) {
    int answer = 0;

    for (int i = 1; i < number + 1; i += 1){
      if(number % i == 0){
        answer += i;
      }
    }


      return answer;
  }
}