/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dailycoding;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

class SumDivisorTest {
  @Test
  void divisor() {
    SumDivisor sumDivisor = new SumDivisor();

    Assertions.assertEquals(6, sumDivisor.solution(5));
    Assertions.assertEquals(28, sumDivisor.solution(12));
    Assertions.assertEquals(18, sumDivisor.solution(10));

  }

  @Test
  void stream() {
    int number = 5;
    int[] array = new int[number];

    for (int i = 0; i < number; i += 1) {
         array[i] = i + 1;
    }
    int sum = Arrays.stream(array).filter(divisor -> number % divisor == 0).sum();


    Assertions.assertEquals(6, sum );
  }
  @Test
  void stream2() {
    int number = 12;
    List<Integer> temp = new ArrayList<>();

    for (int i = 1; i < number +1 ; i+= 1) {
      temp.add(i);
    }
    int sum = temp.stream().mapToInt()


    Assertions.assertEquals(28, sum );
  }
}
