/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dailycoding;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {

  @Test
  void averageTest() {
    Solution solution = new Solution();

    assertEquals(2.5, solution.solution(new int[]{1, 2, 3, 4}));
    assertEquals(5, solution.solution(new int[]{5,5}));
  }
}
