/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dailycoding;

public class HashadNumber {
    public boolean solution(int x) {

        String[] number = String.valueOf(x).split("");
        int sum = 0;

        for(int i = 0; i< number.length; i+=1){
            sum += Integer.parseInt(number[i]);
        }


        return x % sum == 0;
    }
}
