/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dailycoding;

import org.checkerframework.checker.units.qual.A;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

  @Test
  void sample() {
    App app = new App();

    assertEquals(7, app.solution(45));
    assertEquals(229, app.solution(125));
  }
}
