/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dailycoding;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class App {
  public int solution(int n) {
    int answer = 0;

    List<Integer> ternaryList = new ArrayList<>();

    while (n > 0) {
      ternaryList.add(n % 3);
      n /= 3;
    }

    Collections.reverse(ternaryList);

    for (int i = 0; i < ternaryList.size(); i += 1) {
      answer += ternaryList.get(i) * Math.pow(3, i);
    }

    return answer;
  }
}
