/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dailycoding;

public class GuessDayOfWeek {
  public String solution(int a, int b) {
    String[] day = new String[]{"FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU"};

    int[] month = new int[]{31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};


    int date = 0;

    // 날짜 구해주기
    for (int i = 0; i < a - 1; i += 1) {
      date += month[i];
    }

    date += b - 1;

    String answer = day[date % 7];


    return answer;
  }
}
