/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dailycoding;

public class Solution {
  public int solution(int n) {
    int answer = 0;
    String number = String.valueOf(n);


    for(int i =0; i<number.length(); i+=1){
      answer += Integer.parseInt(String.valueOf(number.charAt(i)));
    }

      return answer;
  }
}
