/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dailycoding;

public class Solution {
    public int[] solution(int x, int n) {

        int[] answer = new int[n];

        for(int i = 0; i< n; i+=1 ) {
            answer[i] += x * (i + 1);
        }
        return answer;
    }
}